Lab 2
BGG-Dev/FLabs pull request #3
Opened 2022-06-07 19:13 UTC by BGG-Dev

2022-06-09 02:09 UTC, GasperPaul requested changes
Rework this.

2022-06-09 02:09 UTC, GasperPaul commented on Lab2/KTree/app/KTree.hs
> +data KTree = EmptyKTree | KTree Point KTree KTree
Extending my comment on `Point` this should be `data KTree Int = EmptyKTree Int | KTree Point KTree KTree`.

See how we don't need dimension `Int` in the second condtructor, as we can derive it from `Point`.

Ideally this should be a dependent type, but that is too much.

2022-06-15 16:26 UTC, BGG-Dev commented on Lab2/KTree/app/Main.hs
> +               pf
Suggested changes have been applied.

2022-06-15 16:26 UTC, BGG-Dev commented on Lab2/KTree/app/KTree.hs
> +module KTree where
Suggested changes have been applied.

2022-06-15 16:26 UTC, BGG-Dev commented on Lab2/KTree/app/KTree.hs
> +getCdr :: Point -> Int -> Double
Suggested changes have been applied.

2022-06-15 16:28 UTC, BGG-Dev commented on Lab2/KTree/app/KTree.hs
> +getCdr (Point coords _) k = coords !! k
I don't think we need to process this exception.
If Haskell list does not process the "index out of bound" exception - why should we? Index out of bound exception is not a problem of getCoord method, it is a problem of code, which calls getCoord with incorrect argument, so that code has to deal with exception by itself?

2022-06-15 16:39 UTC, BGG-Dev commented on Lab2/VoidList/app/VoidList.hs
> +data Void = forall e. (Eq e, Show e, Typeable e) => Void e
In this case, my understanding of "Void" is the same as in C language - type-erased.
When we create void pointer to some memory location in C - we lose type information of that location (unless we have other non-void pointers to that memory), we "erase" our knowledge of type for that location in some sense.
By calling my type-erasing container "Void", I tried to show, that this container does exactly what void * does in C.
Yes, in real-world haskell I would not call this type "Void" - this is haskell, not C.
But in this lab I just tried to show my understanding of analogy between void * in C and type-erasing container in haskell.

2022-06-15 16:40 UTC, BGG-Dev commented on Lab2/VoidList/app/VoidList.hs
> +position :: Void -> [Void] -> Int
Suggested changes have been applied.
Although I had to apply constraints to generic type t in type annotation of position like this:
position :: (Eq t) => (Show t) => (Typeable t) => t -> [Void] -> Int

2022-06-15 17:14 UTC, BGG-Dev commented on Lab2/KTree/app/KTree.hs
> +data Point = EmptyPoint | Point [Double] Int
Maybe I'll do something with this problem in lab 3, since it just requires expand lab 2 tree features.

2022-06-16 01:59 UTC, GasperPaul commented on Lab2/KTree/app/KTree.hs
> +getCdr (Point coords _) k = coords !! k
By that logic we should not process any exceptions. We need to safeguard the caller from any problems that may arise from usage not enforced by API. If we do not restrict `k` here, then caller is allowed to call it with any `Int` value and we need to deal with that.

As to why Haskell lists are not dealing with the issue — because they don't know how, this is application-specific. General-purpose data structures are always a compromise, as the library authors don't know how you will use them and cannot optimise for that case, that's why we should use our own data structures with additional restrictions on when possible.

Finally, the idea of exceptions is alien to the functional programming. Haskell authors implementedd it this way because it was a customary solution at the time and to facilitate compatibility with C\C++ code. Nowadays we know that exceptions are to be avoided. The go-to error handling technique in FP is using `Maybe` or `Either` types:
```haskell
-- these are in Prelude, you don't need to define them
data Maybe a = Some a | None
data Eihter a b = Left a | Right b

-- using Maybe
tryGetCdr :: Point -> Int -> Maybe Double
tryGetCdr EmptyPoint = Some 0
tryGetCdr (Point coords _) k
  | 0 <= k < len coords = Maybe (coords !! k)
  | otherwise           = None

-- using Either to save error info
-- you may want to use custom type with additional data instead of String
getCdr :: Point -> Int -> Either String Double
getCdr EmptyPoint = Right 0
getCdr (Point coords _) k
  | 0 <= k < len coords = Right (coords !! k)
  | otherwise           = Left ("Index " ++ show k ++ " is out of bounds."
```

Because `Maybe` and `Either` are monads there are easy ways we can use them with usual data-processing functions that are expecting plain data:
```haskell
f :: Num a => a -> a
f x = x + 1

-- will print "Maybe 11"
main = do
  print $ fmap f mx
  where
    mx = Maybe 10
```

This is called Railway Oriented Programming.

2022-06-16 02:11 UTC, GasperPaul commented on Lab2/VoidList/app/VoidList.hs
> +data Void = forall e. (Eq e, Show e, Typeable e) => Void e
Your understanding is not entirely correct.

In C `void` is not type-erased "generalised" type. It's unit-type, for which Haskell analogue would be `()`. Moreover, C doesn't allow you to manipulate `void` as a regular type, only use it in some specific conditions, namely, function definitions.  You cannot create a variable of type `void`. The closest C equivalent for your `Void` type is actually a void pointer `void*` that can point to any unstructured data, as you described yourself.

And while they share a word in the name they are very different types. `void*` _is_ a real type that can be used as a variable type etc. The naming in C is just confusing: void pointers are not pointing to instances of `void`.

So, when reading your code people will think `Void` is a typename for `()`. I'm ok with you keeping the name here, but don't use it in other code.

2022-06-16 02:12 UTC, GasperPaul commented on Lab2/KTree/app/Main.hs
> +               pf
> Suggested changes have been applied.

Try "Fixed". Easier to type.

2022-06-16 02:14 UTC, GasperPaul commented on Lab2/VoidList/app/VoidList.hs
> +position :: Void -> [Void] -> Int
Sure, the constraint is forced because of the definition of `Void` where you require `Typeable`.

2022-06-16 03:50 UTC, GasperPaul commented on Lab2/KTree/app/KTree.hs
> +data Point = EmptyPoint | Point [Double] Int
There are a few issues here.

> This feature by itself makes haskell lists unusable for representing math points.

Yes and no. Are Haskell lists a representation of math-like points? No. Can they be used to represent them? Yes.

Lists not being points is why you need to define a special type `Point` for them. But because the _internal_ representation of the point in this type uses (mutable) lists doesn't mean that the external API of `Point` should consider it mutable. If anything, you should use `Point` to restrict the API of the list.

> These two facts make haskell lists a truly terrible data structure for representing points.

Indeed. You should consider using tuples or `Data.Array` (which is expected to be rapid access).

But I also want to stress that performance should not be your first consideration when writing in Haskell — as with any other high-level garbage-collected language, Haskell runtime is not efficient. Using "Haskell" and "performance" in the same sentence is almost an oxymoron. (Like it is for Python, Java, etc.)

Each language has its purposes. Haskell allows us to reason about types and their _behaviour_, instead of their internals and how performant that makes them. That's why it's tough to find any info on the internal implementation of Haskell's native types: it's unimportant. Where C standard may require the implementing compiler to do things in a certain way (like arrays being continuous memory blocks), Haskell specification only defines how types should behave, their API. It's so happend that GHC, the most widespread Haskell compiler, implements `[]` using linked lists. Another compiler may choose to use some other internal representation. The guarantee here is the behaviour, the API. Not performance.

We choose Haskell to express ideas more concisely, to eliminate errors using a rigorous type system and immutability (which is also horrible because of memory allocations), not because of its performance. If performance is the issue, you need to choose a different language, like C or C++.

These are essential things to understand. Different tasks may require different languages (and, possibly, compilers). Encapsulation is important for types — internal representation should not dictate type usefulness.

> I used haskell list just for one reason: simplicity.

I'm totally ok with that. No need to use complex types here.

>I decided to keep point dimension in Point type for pure performance reason, since I use point dimension in my program a lot.

This is a non-sequitur. Regardless of your `Point` internal structure, there is no reason to keep size in it.

I understand that you don't want to call `length` on each node; it's reasonable. But this still doesn't explain why you put it in each point.

How does keeping size inside each point help the performance? Well, the only place you use it is the `getDim` function. In turn, it's used to get the index of an axis along which a new point is added in `kNext`. But in all these cases where you often call `getDim`, you can use the value encoded in the tree itself. You can calculate it once by extracting it from the tree definition, as it's nonsense to have a tree with points with different dimensions. Your calling `getDim` many times is more performance heavy than adding that value into the tree definition. It's also a memory waste and data duplication.

But maybe you're using it to ensure data cohesion and structural integrity? No, you're not even checking the dimensions in `getDim` as we saw before when discussing `!!`. (On a side note, you don't actually need this to ensure integrity either.)

Consider this code:

```haskell
-- note the additional Int in constructors
data KdTree = EmptyKdTree Int | KdTree Int Point KdTree KdTree

getDim (Point coords) = length coords

addPointToKdTree point tree = add point tree 0 
  where
    add point EmptyKdTree _ = KdTree (getDim point) Point EmptyKdTree EmptyKdTree
    add newpoint (KdTree dim point left right) k
      |  newCoord <= oldCoord = KdTree point (add newpoint left knext) right
      | otherwise             = KdTree point left                      (add newpoint right knext)
      where
        newCoord = getCoord newpoint k
        oldCoord = getCoord point k 
        knext = mod (k+1) dim
```

Here, we call `length` in only one unique case and store the value in the tree itself, saving the memory and time for `getDim` calls in `add`.

> For this small lab, I decided to check by myself, if all points I add to tree have same dimension

Bad news, you don't. There is no code where you check for the dimensions of the added point. And even then, I would argue, you should call `length` for that.

2022-06-17 19:29 UTC, merged